name: rabudame_web
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_screenutil: ^5.5.3+2
  cached_network_image: ^3.2.1

  # Dart data class
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0

  equatable: ^2.0.3
  google_fonts: ^3.0.1
  go_router: ^4.2.7
  flutter_native_splash: ^2.2.7

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  flutter_gen_runner:
  flutter_launcher_icons: "^0.10.0"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/background/
    - assets/json/
    - assets/character/

flutter_icons:
  image_path: "assets/favicon.png"
  web:
    generate: true
    image_path: "assets/favicon.png"
    background_color: "#000000"
    theme_color: "#000000"

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: false
