name: rabudame_web
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.4

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_screenutil: ^5.5.4
  cached_network_image: ^3.2.2

  # Dart data class
  json_serializable: ^6.5.1
  json_annotation: ^4.7.0

  equatable: ^2.0.5
  google_fonts: ^3.0.1
  flutter_native_splash: ^2.2.11
  scroll_to_index: ^3.0.1
  flutter_layout_grid: ^2.0.1
  url_launcher: ^6.1.6

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1
  build_runner: ^2.3.0
  flutter_gen_runner:
  flutter_launcher_icons: "^0.10.0"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/background/
    - assets/json/
    - assets/character/

flutter_icons:
  image_path: "assets/favicon.png"
  web:
    generate: true
    image_path: "assets/favicon.png"
    background_color: "#000000"
    theme_color: "#000000"

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: false
