name: rabudame_web
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+2
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: 3.10.1

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_screenutil: ^5.8.1
  cached_network_image: ^3.2.3

  # Dart data class
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1

  equatable: ^2.0.5
  google_fonts: ^4.0.4
  flutter_native_splash: ^2.3.0
  scroll_to_index: ^3.0.1
  flutter_layout_grid: ^2.0.3
  url_launcher: ^6.1.11

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1

  # Run scripts
  path: ^1.8.3
  args: ^2.3.1
  process_run: ^0.13.0
  html: ^0.15.0
  crypto: ^3.0.2

dependency_overrides: 
  image: ^4.0.17

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/background/
    - assets/json/
    - assets/character/

flutter_icons:
  image_path: "assets/favicon.png"
  web:
    generate: true
    image_path: "assets/favicon.png"
    background_color: "#000000"
    theme_color: "#000000"

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: false
